# Sleuteltypen: opbouw zoals autosleutel-enschede.nl, teksten eigen voor Hengelo.
# Velden: slug, naam, kop, icoon, prijs (CONFIG-naam), kort, herken, merken, foto (bestand, alt), antwoord,
#         tekst [(kop, alinea)], meenemen [..], faq [(v, a)]
# Prijzen altijd "vanaf"; bedragen gelijk aan CONFIG in build.py. Nooit een prijs bij "alle sleutels kwijt".

SLEUTELTYPEN = [
    dict(slug="transpondersleutel-bijmaken", naam="Transpondersleutel", kop="Transpondersleutel bijmaken", icoon="chip", prijs="P_TRANS",
         kort="De 'gewone' sleutel met een chip in de kop, met of zonder knopjes.",
         herken="Een vaste metalen baard met een kunststof kop. De chip zit onzichtbaar in die kop; soms zitten er knopjes op, vaak ook niet.",
         merken="Toyota, Suzuki, Nissan, Dacia, Hyundai, Kia, oudere Volkswagen, Opel, Ford, Peugeot en Citroën, en veel bestelwagens",
         foto=("werkplaats-voorraad-behuizingen-hengelo.jpg", "Sleutelspecialist bij de voorraadkasten met sleutels, chips en behuizingen per merk"),
         antwoord="Een transpondersleutel bijmaken kost vanaf € 60, inclusief frezen, programmeren en btw. Wij lezen de chip van uw werkende sleutel uit en zetten die over in de nieuwe; meestal bent u in 20 tot 30 minuten klaar. Een sleutel zonder chip past wel in het slot, maar de motor slaat er niet mee aan.",
         tekst=[("Wat de chip doet",
                 "Draait u de sleutel om, dan stelt de auto de chip een versleutelde vraag. Alleen bij het goede antwoord laat de startonderbreker de motor starten. Een sleutel bijmaken is daarom twee handelingen: de baard op maat frezen en de chip programmeren. Beide doen wij in één bezoek."),
                ("Met of zonder knopjes",
                 "Zonder knopjes is dit de eenvoudigste autosleutel: baard en chip, vanaf € 60. Met knopjes zit er ook een zender in voor het openen op afstand. Die leren wij apart in op de auto, en dan komt de prijs hoger uit, afhankelijk van merk en bouwjaar."),
                ("Bestelwagens",
                 "Transit, Vivaro, Transporter, Ducato, Berlingo: bedrijfswagens rijden vaak jaren rond op één sleutel. Raakt die kwijt, dan staat de bus stil. Een reservesleutel maken wij op dezelfde manier als bij een personenauto."),
                ("Versleten baard",
                 "Gaat de sleutel steeds stroever in het slot? Dan is de baard afgesleten. Wij frezen de nieuwe op code, niet als kopie van de versleten baard, zodat hij weer soepel draait.")],
         meenemen=["Uw werkende sleutel", "De auto, zodat wij de nieuwe sleutel meteen testen"],
         faq=[("Mijn sleutel heeft geen knopjes. Zit er dan wel een chip in?", "Bij vrijwel elke auto van na eind jaren negentig wel. Wij zien het in een paar seconden."),
              ("Kan de schoenmaker of sleutelkiosk dit ook?", "Die kan een baard slijpen, maar de chip programmeren niet. Dan gaat het portier open en blijft de motor uit."),
              ("Hoe lang duurt het?", "Als kopie van een werkende sleutel meestal 20 tot 30 minuten.")]),

    dict(slug="klapsleutel-bijmaken", naam="Klapsleutel", kop="Klapsleutel bijmaken", icoon="klap", prijs="P_KLAP",
         kort="De sleutel met de uitklapbare baard en knopjes op de behuizing.",
         herken="De metalen baard springt met een knopje uit de behuizing. Op de behuizing zitten twee of drie knopjes voor openen, sluiten en soms de achterklep.",
         merken="Volkswagen, Audi, Seat, Škoda, Opel, Ford, Fiat, Peugeot, Citroën, Hyundai en Kia",
         foto=("opel-astra-klapsleutel-hengelo.jpg", "Twee bijgemaakte Opel-klapsleutels, met de grijze Opel Astra op de achtergrond"),
         antwoord="Een klapsleutel bijmaken kost vanaf € 130. Daarin zitten de behuizing, de gefreesde baard, de chip en het inleren van de afstandsbediening. Meestal is hij klaar terwijl u wacht. Is alleen de behuizing kapot, dan kan uw eigen elektronica over in een nieuwe behuizing, vanaf € 49,95.",
         tekst=[("Drie onderdelen in één sleutel",
                 "Een klapsleutel combineert een baard voor het slot, een transponderchip voor de startonderbreker en een zender voor de centrale vergrendeling. Alle drie moeten kloppen. Bij een kopie nemen wij de chipgegevens van uw werkende sleutel over en koppelen wij de zender aan de auto."),
                ("Kapot is niet altijd nieuw",
                 "Springt de baard niet meer uit, is het plastic gescheurd of reageren de knopjes niet? Vaak is de elektronica nog prima. Wij zetten chip en printplaat over in een nieuwe behuizing en frezen een nieuwe baard: vanaf € 49,95, zonder programmeren."),
                ("Merken met eigen regels",
                 "Bij Volkswagen, Audi, Seat en Škoda verschilt het systeem per generatie; uw kenteken bepaalt de precieze prijs. Peugeot en Citroën tot ongeveer 2005 vragen om de pincode uit de autopapieren. Laat u twee sleutels tegelijk maken, dan krijgt u korting op de tweede, in overleg.")],
         meenemen=["Uw werkende sleutel", "De auto, zodat wij de afstandsbediening meteen inleren en testen"],
         faq=[("Waarom is een klapsleutel duurder dan een gewone sleutel?", "Er zit een zender in die apart op de auto moet worden ingeleerd, en de uitklapbare behuizing is duurder."),
              ("Mijn klapsleutel klapt niet meer uit. Heb ik een nieuwe nodig?", "Meestal niet. Een nieuwe behuizing met uw eigen chip en zender lost het op, vanaf € 49,95."),
              ("Kan ik een behuizing van internet laten ombouwen?", "Soms, maar vaak past zo'n behuizing net niet op de originele printplaat. Onze behuizingen passen, en de baard frezen wij op code.")]),

    dict(slug="smartkey-bijmaken", naam="Smartkey", kop="Smartkey / keyless sleutel bijmaken", icoon="smart", prijs="P_SMART",
         kort="U start met een knop; de sleutel blijft in uw zak of tas.",
         herken="De auto heeft een startknop. De sleutel heeft geen vaste baard, of alleen een noodsleutel die uit de behuizing schuift.",
         merken="BMW, Mini, Mercedes-Benz (tot en met 2014), Audi, Volvo, Jaguar, Land Rover, Jeep, Nissan, Toyota, Hyundai, Kia, Mazda, Ford en Renault",
         foto=("bmw-x1-smartkey-hengelo.jpg", "Twee bijgemaakte BMW-smartkeys in de hand, met de BMW X1 op de achtergrond"),
         antwoord="Een smartkey bijmaken kost vanaf € 150, inclusief het inleren op de auto. Bij keyless is de beveiliging strenger dan bij een klapsleutel, en per merk is andere apparatuur nodig. Voor de meeste merken en bouwjaren doen wij het zelf, meestal terwijl u wacht. Op basis van uw kenteken weet u vooraf of het bij uw auto lukt.",
         tekst=[("Hoe keyless werkt",
                 "Loopt u naar de auto, dan zoekt hij draadloos contact met de sleutel in uw zak. Klopt het signaal, dan gaan de deuren open. Bij het drukken op de startknop controleert de auto het opnieuw. Daarom moet een nieuwe smartkey precies op uw auto worden aangemeld."),
                ("Eén smartkey is te weinig",
                 "Veel keyless auto's worden met één sleutel verkocht. Is die weg, dan gaat de auto niet open en niet aan. Een tweede smartkey laten maken zolang de eerste werkt, is goedkoper en een stuk rustiger dan wachten tot het misgaat."),
                ("Wat wel en niet kan",
                 "Smartkeys van de meeste Europese en Aziatische merken maken wij, als kopie en als nieuwe sleutel zonder origineel. Mercedes-Benz personenwagens vanaf 2015 maken wij niet; de Sprinter W906 tot en met 2017 wel. BMW en Mini: prijs op aanvraag per model. Een enkel zeer recent systeem kan alleen via de dealer; dat zeggen wij vooraf."),
                ("Nieuwer is duurder",
                 "Hoe jonger de auto, hoe zwaarder de beveiliging en hoe meer werk het inleren. De vanaf-prijs geldt voor de eenvoudigere systemen. Het bouwjaar zit in uw kenteken, dus u krijgt de prijs voordat wij beginnen.")],
         meenemen=["De auto: een smartkey wordt op de auto zelf ingeleerd", "Uw werkende smartkey, als u die heeft"],
         faq=[("Moet de auto mee voor een smartkey?", "Ja. Het inleren gaat via de diagnoseaansluiting van de auto. Kunt u niet komen, dan komen wij aan huis."),
              ("Kan ik met een lege batterij nog starten?", "Meestal wel: houd de sleutel tegen de startknop of op de plek die in het instructieboekje staat. Lukt het niet, bel dan even."),
              ("Waarom is een smartkey duurder?", "De sleutel zelf kost meer en het inleren vraagt apparatuur per merk en meer tijd.")]),

    dict(slug="sleutelkaart-bijmaken", naam="Sleutelkaart", kop="Sleutelkaart bijmaken", icoon="kaart", prijs="P_KAART",
         kort="De platte kaart die u in het dashboard schuift of gewoon bij u houdt.",
         herken="Een platte kaart van ongeveer creditcardformaat met knopjes. Vooral bekend van Renault en Dacia.",
         merken="Renault (Mégane, Scénic, Clio, Captur, Kadjar, Laguna, Espace) en Dacia",
         foto=("renault-kadjar-sleutelkaart-hengelo.jpg", "Twee bijgemaakte Renault-sleutelkaarten in de hand, met de Renault Kadjar op de achtergrond"),
         antwoord="Een sleutelkaart bijmaken kost vanaf € 130, inclusief het aanmelden op de auto. Kaarten voor Renault en Dacia maken wij meestal terwijl u wacht. Doen de knopjes het niet meer of is de kaart gescheurd, dan is repareren vaak mogelijk.",
         tekst=[("Insteekkaart of handsfree",
                 "Oudere Renaults zoals de Mégane II, Scénic II en Laguna II hebben een kaart die in een gleuf in het dashboard gaat. Nieuwere modellen zoals de Clio IV en V, Captur en Kadjar werken handsfree: de kaart blijft in uw zak. Beide maken wij bij; de handsfree kaart vraagt meer werk."),
                ("Waarom kaarten slijten",
                 "Een kaart zit in de broekzak, buigt mee en krijgt tikken. De knopjes slijten, de hoeken scheuren bij de noodsleutel. Start de auto nog, dan is de chip in orde en is een nieuwe kaartbehuizing met uw eigen elektronica vaak genoeg. Met een foto via WhatsApp hoort u wat het kost.")],
         meenemen=["Uw werkende kaart, als u die heeft", "De auto, want de kaart wordt op de auto aangemeld"],
         faq=[("Mijn Renault meldt 'kaart niet herkend'. Is de kaart stuk?", "Vaak is de batterij leeg of zijn de contacten in de kaart versleten. Dat testen wij in een paar minuten."),
              ("De kaart is gescheurd maar de auto start nog.", "Dan is de chip goed. Een nieuwe kaartbehuizing met uw eigen elektronica is dan meestal genoeg."),
              ("Hoe lang duurt het bijmaken van een sleutelkaart?", "Meestal 20 tot 30 minuten, terwijl u wacht.")]),

    dict(slug="autosleutel-reparatie", naam="Reparatie", kop="Autosleutel repareren", icoon="rep", prijs="P_REP",
         kort="Knopjes, behuizing, veer of losse chip: repareren is bijna altijd goedkoper.",
         herken="De sleutel doet het half: knopjes reageren slecht, de behuizing is gebroken, de baard zit los of klapt niet uit, of de sleutel is nat geworden.",
         merken="alle merken; het vaakst Volkswagen, Ford, Opel, Peugeot, Renault en Fiat",
         foto=("werkplaats-reparatie-werkbank-hengelo.jpg", "Sleutelspecialist repareert een autosleutel aan de werkbank in de werkplaats in Enschede"),
         antwoord="Een autosleutel repareren kost vanaf € 30. Een nieuwe behuizing voor een vaste sleutel kost vanaf € 35, voor een klapsleutel vanaf € 49,95. Uw eigen chip en zender gaan mee, dus opnieuw programmeren is niet nodig. Printplaat- of soldeerwerk prijzen wij na een foto via WhatsApp.",
         tekst=[("Wat wij repareren",
                 "Afgesleten of afgebroken knopjes, gescheurde behuizingen, klapveren die het opgeven, losgeraakte chips, batterijcontacten met corrosie en sleutels die nat zijn geworden. Wij solderen op de printplaat zelf en vervangen alleen wat echt stuk is."),
                ("Nieuwe behuizing, dezelfde sleutel",
                 "Is de behuizing op, dan verhuist uw elektronica naar een nieuwe behuizing en frezen wij de baard opnieuw. Voor de auto verandert er niets; voor u voelt de sleutel weer als nieuw."),
                ("Wanneer repareren niet meer kan",
                 "Is de chip zelf beschadigd of de printplaat gebroken, dan helpt een nieuwe behuizing niet. Dan wordt het een nieuwe sleutel, die meestal dezelfde dag klaar is. Dat zien wij snel en dat zeggen wij ook: u betaalt geen reparatie die niets oplevert."),
                ("Nat geworden",
                 "Haal de batterij eruit, druk niet op de knopjes en laat de sleutel niet wekenlang liggen. Hoe eerder wij de printplaat schoonmaken, hoe groter de kans dat hij te redden is.")],
         meenemen=["De kapotte sleutel", "Uw reservesleutel, als u die heeft: dan vergelijken wij de werking"],
         faq=[("Moet een sleutel met een nieuwe behuizing opnieuw worden ingeleerd?", "Nee. Chip en zender blijven dezelfde, dus de auto herkent de sleutel meteen."),
              ("Na een nieuwe batterij doet mijn sleutel niets meer.", "Vaak zit de batterij verkeerd om of is een contactlipje verbogen. Soms moet de sleutel opnieuw met de auto worden gesynchroniseerd. Kom even langs."),
              ("Wat kost een reparatie?", "Vanaf € 30. Een behuizing voor een vaste sleutel vanaf € 35, voor een klapsleutel vanaf € 49,95; printplaatwerk na een foto.")]),
]
