# Merken L tot en met Z. Zie data_merken_1.py voor de velden.

MERKEN_2 = [
dict(naam="Land Rover", slug="land-rover", prijsregel="staffel", foto=("land-rover-range-rover-smartkey-hengelo.jpg", "Twee Range Rover-smartkeys in de hand, met de zwarte Range Rover op de achtergrond", "Range Rover: twee smartkeys bijgemaakt"),
     intro="Range Rover, Discovery, Defender en Freelander: Land Rover stapte met de Discovery 3 en de eerste Range Rover Sport over op smartkeys, en kreeg met de Evoque en Discovery 4 keyless start. De oudere Freelander en Defender hebben nog een vaste sleutel met chip. Land Rover en Jaguar gebruiken sinds 2008 dezelfde sleutelsystemen.",
     typen=[("Tot ongeveer 2006", "Vaste sleutel met chip en afstandsbediening, bij de Freelander I, Discovery II, de oude Defender en de Range Rover P38."),
            ("2006 – 2012", "Smartkey met startknop, bij de Discovery 3, Range Rover Sport I, Freelander 2 en latere Range Rover L322."),
            ("2012 en nieuwer", "Smartkey met keyless, bij de Evoque, Discovery 4 en 5, Discovery Sport, Range Rover L405 en L460, Velar en de nieuwe Defender.")],
     extra=[("Reservesleutel voor een Land Rover", "Een Land Rover-smartkey is geen goedkope sleutel om kwijt te raken. Laat een tweede maken zolang de eerste werkt; dan is het een kopie en blijft de auto rijden.")],
     modellen=["Defender", "Discovery en Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque"],
     faq=[("Wat kost een sleutel voor een Range Rover of Discovery?", "Een smartkey vanaf € 150, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("Mijn Freelander heeft een gewone sleutel. Kan dat ook?", "Ja. Een transpondersleutel kost vanaf € 60, een klapsleutel vanaf € 130."),
          ("Geen enkele Land Rover-sleutel meer. Wat nu?", "Bij de meeste bouwjaren maken wij dan een nieuwe sleutel en wissen wij de verloren sleutels; de auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="Lexus", slug="lexus", prijsregel="staffel", foto=None,
     intro="Lexus is het luxemerk van Toyota en gebruikt dezelfde techniek. De oudere IS 200 en RX 300 hebben een vaste sleutel met chip en afstandsbediening; vrijwel elke Lexus vanaf ongeveer 2005 heeft een smartkey met startknop, ook de hybrides. Die smartkeys zien wij dan ook het vaakst.",
     typen=[("Tot ongeveer 2005", "Vaste sleutel met chip en afstandsbediening, bij de IS 200 en 300, RX 300, GS 300 en LS 400 en 430."),
            ("2005 – 2015", "Smartkey met startknop, bij de IS II, RX II en III, GS III, CT 200h en LS IV."),
            ("2015 en nieuwer", "Smartkey van een nieuwe generatie, bij de NX, UX, RX IV en V, ES, IS III, LC en RZ. Voor de allerjongste modellen is soms de dealer nodig.")],
     extra=[("Hybride", "De smartkey van een Lexus-hybride is dezelfde als bij de benzineversie en wordt op dezelfde manier aangemeld.")],
     modellen=["CT 200h", "IS", "ES", "GS", "LS", "UX", "NX", "RX", "RZ", "LC", "RC", "LBX"],
     faq=[("Wat betaal ik voor een extra Lexus-smartkey?", "Vanaf € 150, inclusief programmeren. Het bouwjaar bepaalt de exacte prijs."),
          ("Kunnen jullie een Lexus-sleutel maken als alles kwijt is?", "Bij de meeste bouwjaren wel. Stuur uw kenteken, dan hoort u het vooraf.")]),

dict(naam="Mazda", slug="mazda", prijsregel="staffel", foto=("mazda-cx-5-smartkey-hengelo.jpg", "Twee Mazda-smartkeys in de hand, met de rode Mazda CX-5 op de achtergrond", "Mazda CX-5: twee smartkeys bijgemaakt"),
     intro="Een oudere Mazda 2, 3 of 6 heeft een vaste sleutel of klapsleutel met chip. De huidige Mazda 2, 3, CX-30 en CX-5 werken met een smartkey en startknop. Bij Mazda slijten de knopjes van de smartkey vaak eerder dan de elektronica; dan is repareren een optie.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip en afstandsbediening, bij de 323, 626, Premacy, MX-5 NB en de eerste Mazda 2 en 6."),
            ("2008 – 2014", "Klapsleutel of vaste sleutel met knopjes, soms al een smartkey, bij de Mazda 2 II, 3 II, 5, 6 II en CX-7."),
            ("2014 en nieuwer", "Smartkey met keyless start, bij de Mazda 2 III, 3 III en IV, 6 III, CX-3, CX-30, CX-5, CX-60, MX-30 en MX-5 ND.")],
     extra=[("Knopjes versleten", "Doet de sleutel het nog, maar reageren de knopjes slecht? App ons een foto. Vaak is een reparatie genoeg, vanaf € 30.")],
     modellen=["Mazda 2", "Mazda 3", "Mazda 5", "Mazda 6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-30", "MX-5", "CX-7", "323", "626", "Premacy", "RX-8"],
     faq=[("Wat kost een smartkey voor een CX-5?", "Vanaf € 150, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("Mijn Mazda-sleutel is kapot, maar de auto start nog.", "Dan is de chip in orde. Meestal volstaat een reparatie of een nieuwe behuizing met uw eigen elektronica.")]),

dict(naam="Mercedes-Benz", slug="mercedes-benz", prijsregel="mercedes", foto=("mercedes-slk-autosleutel-hengelo.jpg", "Mercedes-sleutel met sleutelhanger in de hand, met de zwarte Mercedes SLK op de achtergrond", "Mercedes SLK: sleutel bijgemaakt en ingeleerd"),
     intro="Mercedes-Benz personenwagens vanaf 2015 maken wij niet; de Sprinter W906 tot en met 2017 wel. Voor Mercedes tot en met bouwjaar 2014 kunt u bij ons terecht: de vaste sleutel met chip van de oudere modellen en de bekende infraroodsleutel met chroomrand. Wij zeggen het liever vooraf dan dat u voor niets komt; op uw kenteken ziet u meteen of het bij uw Mercedes kan.",
     typen=[("Tot ongeveer 1997", "Vaste sleutel met chip, bij de W124 en vroege W202 en W210. Kopie van uw werkende sleutel."),
            ("1997 – 2014", "Infraroodsleutel met chroomrand, met of zonder keyless, bij de A-, B-, C-, E- en S-klasse, CLK, CLS, ML, GLK, Vito en Sprinter. Prijs vooraf op uw kenteken."),
            ("2015 en nieuwer", "Sleutels voor personenwagens uit deze jaren maken wij niet. De Sprinter W906 tot en met 2017 wel.")],
     extra=[("Wat wij wel en niet doen", "Mercedes tot en met 2014: ja, met een prijs vooraf. Personenwagens vanaf 2015: nee, daarvoor verwijzen wij u naar de dealer. Sprinter W906: tot en met 2017 wel.")],
     modellen=["A-klasse (W168, W169, W176)", "B-klasse (W245, W246)", "C-klasse (W202, W203, W204)", "CLA (C117)", "CLK", "CLS (C219)", "E-klasse (W210, W211, W212)", "S-klasse (W220, W221)", "SLK", "SL", "ML en GLK", "GLA (X156)", "Vito en Viano", "Sprinter (W906 tot en met 2017)", "Citan"],
     faq=[("Mijn Mercedes is van 2017. Kunnen jullie daar een sleutel voor maken?", "Nee. Mercedes-Benz personenwagens vanaf 2015 maken wij niet; de Sprinter W906 tot en met 2017 wel."),
          ("Wat betaal ik voor een sleutel van een Mercedes van 2014 of ouder?", "Dat verschilt per model en bouwjaar. U krijgt de prijs vooraf op basis van uw kenteken."),
          ("Kan het zonder werkende Mercedes-sleutel?", "Bij modellen tot en met 2014 meestal wel. De auto moet erbij zijn.")]),

dict(naam="Mini", slug="mini", prijsregel="bmw", foto=("mini-clubman-smartkey-hengelo.jpg", "Twee ronde Mini-smartkeys in de hand, met de Mini Clubman op de achtergrond", "Mini Clubman: twee smartkeys bijgemaakt"),
     intro="Mini hoort bij BMW en gebruikt dezelfde zwaar beveiligde systemen. De eerste generatie heeft een sleutel met EWS-chip, daarna kwam de ronde smartkey van de R56 en Clubman, en sinds 2014 een nieuwe generatie met keyless. Net als bij BMW noemen wij geen tabelprijs: u krijgt de prijs per model vooraf op uw kenteken.",
     typen=[("2001 – 2006 (R50, R52, R53)", "Sleutel met EWS-chip en afstandsbediening. Kopie van uw werkende sleutel."),
            ("2007 – 2014 (R55 – R61)", "Ronde smartkey voor het CAS-systeem, bij de Cooper, Clubman, Countryman en Paceman."),
            ("2014 en nieuwer (F54 – F60)", "Smartkey van de nieuwe generatie met keyless. Prijs op aanvraag.")],
     extra=[("Prijs op aanvraag", "De systemen van BMW en Mini verschillen per generatie te veel voor één prijs. Stuur uw kenteken; u hoort vooraf of wij uw sleutel kunnen maken en wat het kost.")],
     modellen=["Cooper en Cooper S (R50, R53, R56, F56)", "Cabrio (R52, R57, F57)", "Clubman (R55, F54)", "Countryman (R60, F60, U25)", "Paceman (R61)", "Coupé en Roadster (R58, R59)", "Mini Electric"],
     faq=[("Waarom geen tabelprijs voor Mini?", "Mini draait op BMW-techniek, en die wisselt sterk per generatie. Uw kenteken geeft vooraf de prijs."),
          ("Is de ronde sleutel van mijn Mini na te maken?", "Bij de meeste bouwjaren wel. Heeft u nog een werkende, dan maken wij daar een kopie van.")]),

dict(naam="Mitsubishi", slug="mitsubishi", prijsregel="staffel", foto=None,
     intro="De Colt, Space Star, ASX en Outlander hebben een vaste sleutel of klapsleutel met chip en afstandsbediening. De Outlander PHEV en Eclipse Cross van de laatste jaren werken met een smartkey en startknop. Kleine Mitsubishi's hebben soms een sleutel zonder knopjes; dat is een transpondersleutel.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip, met of zonder afstandsbediening, bij de Colt, Carisma, Space Star I, Pajero en Galant."),
            ("2008 – 2016", "Vaste sleutel of klapsleutel met knopjes, bij de Colt II, Space Star II, ASX, Lancer en Outlander II."),
            ("2016 en nieuwer", "Smartkey met keyless start, bij de Outlander III en IV, Eclipse Cross en ASX II.")],
     extra=[("Outlander PHEV", "De plug-in hybride heeft een smartkey die op dezelfde manier wordt aangemeld als bij de benzineversie.")],
     modellen=["Space Star", "Colt", "ASX", "Eclipse Cross", "Outlander en Outlander PHEV", "Lancer", "Pajero", "L200", "Carisma", "Galant", "Grandis", "i-MiEV"],
     faq=[("Wat kost een Space Star-sleutel?", "Een transpondersleutel vanaf € 60, een klapsleutel vanaf € 130, inclusief programmeren."),
          ("Maken jullie een smartkey voor een Outlander PHEV?", "Voor de meeste bouwjaren wel, vanaf € 150.")]),

dict(naam="Nissan", slug="nissan", prijsregel="staffel", foto=("nissan-navara-autosleutel-hengelo.jpg", "Drie Nissan-sleutels in de hand, met de Nissan Navara op de achtergrond", "Nissan Navara: sleutels bijgemaakt en ingeleerd"),
     intro="Nissan noemt zijn smartkey de Intelligent Key; die zit sinds ongeveer 2010 op veel Qashqai's, Micra's en Juke's. Oudere Micra's, Notes en Almera's hebben een vaste sleutel of klapsleutel met chip. Ook de Navara en bestelwagens als de Primastar en Townstar maken wij bij.",
     typen=[("Tot ongeveer 2009", "Vaste sleutel met chip en afstandsbediening, bij de Micra K11 en K12, Almera, Primera, Note I en X-Trail I."),
            ("2009 – 2017", "Klapsleutel of smartkey, bij de Micra K13, Note II, Juke I, Qashqai J10 en J11, Leaf I en Navara D40."),
            ("2017 en nieuwer", "Smartkey met keyless start, bij de Micra K14, Juke II, Qashqai J12, X-Trail T33, Leaf II, Ariya en Navara D23.")],
     extra=[("Bedrijfswagens", "Navara, Primastar, Townstar en Interstar gebruiken vergelijkbare systemen. Een tweede sleutel voorkomt dat een bedrijfswagen stilstaat.")],
     modellen=["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Pulsar", "Almera", "Primera", "Navara", "Townstar", "Primastar", "Interstar", "NV200", "Pathfinder", "350Z en 370Z"],
     faq=[("Wat kost een sleutel voor een Micra of Qashqai?", "Een klapsleutel vanaf € 130, een smartkey vanaf € 150, inclusief programmeren."),
          ("Mijn Intelligent Key doet het niet meer.", "Vaak is het de batterij of zijn de knopjes versleten. Kom langs of stuur een foto; zo nodig maken wij een nieuwe.")]),

dict(naam="Opel", slug="opel", prijsregel="staffel", foto=("opel-astra-klapsleutel-hengelo.jpg", "Twee bijgemaakte Opel-klapsleutels in de hand, met de grijze Opel Astra op de achtergrond", "Opel Astra: twee klapsleutels bijgemaakt"),
     intro="Corsa, Astra, Insignia, Zafira en Mokka uit de GM-periode hebben bijna allemaal een klapsleutel met twee of drie knopjes. Oudere Opels rijden met een vaste sleutel met chip. De nieuwste Corsa, Mokka en Grandland zijn gebouwd op Peugeot-techniek en hebben een klapsleutel of smartkey zoals Peugeot.",
     typen=[("Tot ongeveer 2004", "Vaste sleutel met chip, afstandsbediening los of ingebouwd, bij de Corsa B en C, Astra F en G, Vectra B, Zafira A en Omega."),
            ("2004 – 2019", "Klapsleutel met twee of drie knopjes, bij de Corsa D en E, Astra H, J en K, Zafira B en C, Insignia A, Meriva, Mokka A en Combo."),
            ("2019 en nieuwer", "Klapsleutel of smartkey op Stellantis-techniek, bij de Corsa F, Mokka B, Crossland, Grandland, Astra L en Combo E.")],
     extra=[("Versleten Opel-klapsleutel", "Een Opel-klapsleutel met losse knopjes of een gebroken scharnier is vaak te repareren. Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95."),
            ("Twee sleutels tegelijk", "Heeft u nog maar één Opel-sleutel, laat er dan meteen twee maken. Op de tweede krijgt u korting, in overleg.")],
     modellen=["Corsa en Corsa-e", "Astra", "Insignia", "Mokka en Mokka-e", "Crossland", "Grandland", "Zafira en Zafira Life", "Meriva", "Adam", "Karl", "Agila", "Vectra", "Omega", "Antara", "Combo", "Vivaro", "Movano"],
     faq=[("Wat kost een sleutel voor een Corsa of Astra?", "Een klapsleutel vanaf € 130, inclusief programmeren. Twee tegelijk: korting op de tweede, in overleg."),
          ("Mijn Opel-klapsleutel is versleten.", "Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95; voor een vaste sleutel vanaf € 35.")]),

dict(naam="Peugeot", slug="peugeot", prijsregel="psa", foto=("peugeot-508-smartkey-hengelo.jpg", "Twee Peugeot-smartkeys in de hand, met de zwarte Peugeot 508 op de achtergrond", "Peugeot 508: twee smartkeys bijgemaakt"),
     intro="De 206, 207, 208, 307, 308 en 3008 hebben bijna allemaal een klapsleutel met twee of drie knopjes. De nieuwste 208, 2008, 308 en 3008 werken met een smartkey en startknop, en de oudste modellen met een vaste sleutel. Bij Peugeots tot ongeveer 2005 is de pincode uit de autopapieren nodig om een sleutel in te leren.",
     typen=[("Tot ongeveer 2005", "Vaste sleutel of klapsleutel met chip, bij de 106, 206, 306, vroege 307, 406, Partner I en Boxer. Pincode uit de autopapieren nodig."),
            ("2005 – 2019", "Klapsleutel met twee of drie knopjes, bij de 107, 207, 208 I, 307, 308 I en II, 3008 I, 5008 I, Partner II en Expert."),
            ("2019 en nieuwer", "Smartkey met keyless start, bij de 208 II, 2008 II, 308 III, 3008 II en III, 5008 II en Rifter.")],
     extra=[("Pincode kwijt", "Een oudere Peugeot vraagt bij het inleren om de code uit de autopapieren. Heeft u die niet meer, dan vragen wij hem op, vanaf € 35.")],
     modellen=["107 en 108", "206 en 206+", "207", "208 en e-208", "2008 en e-2008", "307", "308 en e-308", "3008", "408", "5008", "508", "Rifter en e-Rifter", "Partner", "Expert en Traveller", "Boxer", "RCZ", "Bipper", "1007", "4007 en 4008"],
     faq=[("Vraagt mijn Peugeot om een pincode?", "Alleen bij modellen tot ongeveer 2005. Zonder code vragen wij hem op, vanaf € 35."),
          ("Wat kost een klapsleutel voor een 208?", "Vanaf € 130, inclusief programmeren. De nieuwe 208 met smartkey vanaf € 150."),
          ("De baard van mijn Peugeot-sleutel springt niet meer naar buiten.", "Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95.")]),

dict(naam="Porsche", slug="porsche", prijsregel="staffel", foto=("porsche-boxster-smartkey-hengelo.jpg", "Twee Porsche-sleutels in de hand, met de witte Porsche Boxster op de achtergrond", "Porsche Boxster: twee sleutels bijgemaakt"),
     intro="Porsche hoort bij de Volkswagen-groep. De Cayenne en Macan delen hun sleuteltechniek met Audi; de 911, Boxster en Cayman hebben eigen generaties. Van de sleutel van een 996 of Boxster 986 tot de smartkey van de Cayenne, Macan en Panamera: welke uw Porsche heeft, lezen wij uit uw kenteken.",
     typen=[("Tot ongeveer 2004", "Vaste sleutel of klapsleutel met chip en afstandsbediening, bij de 911 996, Boxster 986 en vroege Cayenne."),
            ("2004 – 2016", "Sleutel in Porsche-vorm met chip en afstandsbediening, soms keyless, bij de 911 997, Boxster en Cayman 987, Cayenne 92A, Panamera 970 en Macan."),
            ("2016 en nieuwer", "Smartkey met keyless, bij de 911 991.2 en 992, 718, Cayenne 9Y0, Panamera 971 en Taycan. Voor de allerjongste modellen is soms de dealer nodig.")],
     extra=[("Prijs per model", "Omdat Porsche Volkswagen-techniek gebruikt, kan de prijs per model afwijken van de vanaf-prijs. Met uw kenteken maken wij er vooraf één prijs van.")],
     modellen=["911", "718 Boxster en Cayman", "Boxster", "Cayman", "Cayenne", "Macan", "Panamera", "Taycan", "924, 944 en 968", "928"],
     faq=[("Wat kost een sleutel voor een Cayenne?", "Een smartkey vanaf € 150, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("Kunnen jullie een sleutel maken voor een oudere 911 of Boxster?", "Ja. Dat is meestal een kopie van uw werkende sleutel met chip en afstandsbediening.")]),

dict(naam="Renault", slug="renault", prijsregel="staffel", foto=("renault-kadjar-sleutelkaart-hengelo.jpg", "Twee Renault-sleutelkaarten in de hand, met de Renault Kadjar op de achtergrond", "Renault Kadjar: twee sleutelkaarten bijgemaakt"),
     intro="Bij Renault denkt u al snel aan de sleutelkaart van de Mégane, Scénic, Clio, Captur en Kadjar. Maar de Twingo, Kangoo en oudere Clio's hebben een klapsleutel of vaste sleutel met chip, en bestelwagens als de Trafic en Master ook. Wij maken ze allemaal bij en repareren kaarten met versleten knopjes.",
     typen=[("Tot ongeveer 2003", "Vaste sleutel met chip en afstandsbediening, bij de Clio II, Twingo I, Mégane I, Laguna I en Kangoo I."),
            ("2003 – 2015", "Insteekkaart in het dashboard bij de Mégane II en III, Scénic II en III, Laguna II en III en Espace IV, of een klapsleutel bij de Clio III, Twingo II, Modus en Kangoo II."),
            ("2015 en nieuwer", "Handsfree sleutelkaart of smartkey, bij de Clio IV en V, Captur, Kadjar, Mégane IV, Austral, Arkana en Zoe.")],
     extra=[("Sleutelkaart repareren", "Doen de knopjes van uw kaart niets meer of is hij gescheurd? Start de auto nog, dan kan de elektronica vaak over in een nieuwe kaartbehuizing. Met een foto via WhatsApp hoort u wat het kost.")],
     modellen=["Twingo", "Clio", "Captur", "Mégane en Mégane E-Tech", "Scénic en Grand Scénic", "Kadjar", "Austral", "Arkana", "Koleos", "Espace", "Laguna", "Talisman", "Zoe", "Renault 5 E-Tech", "Kangoo", "Trafic", "Master", "Modus", "Wind"],
     faq=[("Wat betaal ik voor een extra Renault-kaart?", "Vanaf € 130, inclusief programmeren. Een handsfree kaart vraagt meer werk; uw kenteken bepaalt de precieze prijs."),
          ("Mijn Renault-kaart is gescheurd. Werkt hij nog?", "Meestal wel. Dan gaat uw elektronica over in een nieuwe kaartbehuizing, zonder programmeren."),
          ("Kan het zonder werkende kaart?", "Bij vrijwel alle Renaults wel. De auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="Seat", slug="seat", prijsregel="vag", foto=None,
     intro="De Ibiza, Leon, Arona en Ateca gebruiken dezelfde sleutels als Volkswagen: klapsleutels bij de meeste generaties en een smartkey bij de jongste uitvoeringen. Omdat de systemen van de Volkswagen-groep per generatie verschillen, kan de prijs bij Seat per model afwijken van de vanaf-prijs. Een sleutel voor de Seat Mii kost vanaf € 129.",
     typen=[("Tot ongeveer 2009", "Klapsleutel met chip en afstandsbediening, bij de Ibiza III, Leon I, Toledo, Altea en Alhambra I."),
            ("2009 – 2017", "Klapsleutel van de nieuwere generatie, bij de Ibiza IV, Leon II en III, Mii en Alhambra II. Zonder werkende sleutel soms meer werk."),
            ("2017 en nieuwer", "Klapsleutel of smartkey met keyless, bij de Ibiza V, Leon IV, Arona, Ateca, Tarraco en Cupra-modellen.")],
     extra=[("Seat Mii", "De Mii is technisch een tweeling van de Volkswagen Up en Škoda Citigo. Een sleutel kost vanaf € 129, inclusief programmeren.")],
     modellen=["Mii", "Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Toledo", "Altea", "Alhambra", "Exeo", "Cordoba", "Cupra Formentor, Born en Leon"],
     faq=[("Wat kost een sleutel voor een Ibiza of Leon?", "Een klapsleutel vanaf € 130. Bij Seat kan een model afwijken, dus uw kenteken bepaalt de precieze prijs."),
          ("Wat kost een Mii-sleutel?", "Vanaf € 129, inclusief programmeren.")]),

dict(naam="Škoda", slug="skoda", prijsregel="vag", foto=("skoda-fabia-klapsleutel-hengelo.jpg", "Twee Skoda-klapsleutels in de hand, met de witte Skoda op de achtergrond", "Skoda: twee klapsleutels bijgemaakt"),
     intro="Škoda gebruikt de techniek van de Volkswagen-groep. Een Fabia, Octavia of Superb heeft meestal een klapsleutel, de Kodiaq, Karoq en Enyaq vaak een smartkey. Per generatie verschilt het systeem, dus de prijs kan per model afwijken van de vanaf-prijs; de exacte prijs noemen wij op uw kenteken. Een sleutel voor de Citigo kost vanaf € 129.",
     typen=[("Tot ongeveer 2008", "Klapsleutel met chip en afstandsbediening, bij de Fabia I, Octavia I en Superb I."),
            ("2008 – 2017", "Klapsleutel van de nieuwere generatie, bij de Fabia II, Octavia II en III, Roomster, Yeti, Citigo, Rapid en Superb II."),
            ("2017 en nieuwer", "Klapsleutel of smartkey met keyless, bij de Fabia III en IV, Octavia IV, Scala, Kamiq, Karoq, Kodiaq en Enyaq.")],
     extra=[("Škoda Citigo", "De Citigo deelt zijn techniek met de Volkswagen Up en Seat Mii. Een sleutel kost vanaf € 129, inclusief programmeren.")],
     modellen=["Citigo", "Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Rapid", "Roomster", "Yeti", "Felicia"],
     faq=[("Wat kost een sleutel voor een Octavia of Fabia?", "Een klapsleutel vanaf € 130; de exacte prijs kan per model afwijken en volgt op uw kenteken."),
          ("Wat kost een Citigo-sleutel?", "Vanaf € 129, inclusief programmeren."),
          ("Kan het zonder werkende Škoda-sleutel?", "Bij de meeste bouwjaren wel. Sommige modellen vragen dan meer programmeerwerk; dat hoort u vooraf.")]),

dict(naam="Smart", slug="smart", prijsregel="staffel", foto=None,
     intro="Smart heeft door de jaren heen verschillende technieken gebruikt. De eerste fortwo en forfour gebruiken een eigen sleutel met chip en afstandsbediening; de fortwo en forfour vanaf 2014 zijn gebouwd samen met de Renault Twingo en hebben een klapsleutel of smartkey. Welke generatie uw Smart is en wat daarbij kan, hoort u vooraf op uw kenteken.",
     typen=[("1998 – 2007", "Sleutel met chip en afstandsbediening, bij de City-Coupé, fortwo 450, Roadster en forfour 454."),
            ("2007 – 2014 (fortwo 451)", "Sleutel met chip en afstandsbediening."),
            ("2014 en nieuwer (453)", "Klapsleutel of smartkey op Renault-techniek, bij de fortwo en forfour 453 en de EQ-versies.")],
     extra=[("Eerst uw kenteken", "Bij Smart loopt het per generatie sterk uiteen wat mogelijk is. Stuur uw kenteken en een foto van de sleutel; dan weet u vooraf of wij hem kunnen maken.")],
     modellen=["fortwo (450, 451, 453)", "fortwo cabrio", "forfour (454, 453)", "EQ fortwo en EQ forfour", "Roadster", "Crossblade"],
     faq=[("Wat kost een sleutel voor een Smart fortwo?", "Dat hangt af van de generatie. Een klapsleutel kost vanaf € 130; uw kenteken bepaalt de precieze prijs."),
          ("Kan het zonder werkende Smart-sleutel?", "Stuur uw kenteken, dan hoort u vooraf wat bij uw generatie mogelijk is.")]),

dict(naam="Suzuki", slug="suzuki", prijsregel="staffel", foto=None,
     intro="De Swift, Alto, Splash en Vitara hebben een vaste sleutel met chip, met of zonder afstandsbediening. Nieuwere uitvoeringen van de Swift, Vitara en S-Cross hebben een smartkey met startknop. Suzuki-sleutels zijn eenvoudig van opbouw, en een kopie is meestal snel klaar.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip, met of zonder afstandsbediening, bij de Alto, Wagon R, Ignis I, Swift II, Jimny en Grand Vitara I."),
            ("2008 – 2017", "Vaste sleutel met knopjes of smartkey, bij de Swift III, Splash, Alto VII, SX4, Grand Vitara II en Celerio."),
            ("2017 en nieuwer", "Smartkey met keyless start, bij de Swift IV, Ignis II, Baleno, Vitara, S-Cross en Jimny IV.")],
     extra=[("Sleutel zonder knopjes", "Kleine Suzuki's zoals de Alto en Celerio hebben vaak een sleutel zonder afstandsbediening. Dat is een transpondersleutel, vanaf € 60.")],
     modellen=["Swift", "Alto", "Celerio", "Splash", "Ignis", "Baleno", "Vitara", "S-Cross en SX4", "Grand Vitara", "Jimny", "Across", "Swace", "Wagon R", "Liana"],
     faq=[("Wat kost een Suzuki Swift-sleutel?", "Een transpondersleutel vanaf € 60, een smartkey vanaf € 150, inclusief programmeren."),
          ("Kan het zonder originele Suzuki-sleutel?", "Bij vrijwel alle modellen wel; de auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="Toyota", slug="toyota", prijsregel="staffel", foto=None,
     intro="Een oudere Aygo, Yaris of Corolla heeft een vaste sleutel of klapsleutel met chip. Bij de hybrides en de jongere Yaris, C-HR en RAV4 hoort vrijwel altijd een smartkey met startknop. Toyota-sleutels zijn goed te programmeren, bij de meeste modellen ook als er geen werkende sleutel meer is.",
     typen=[("Tot ongeveer 2010", "Vaste sleutel met chip, afstandsbediening los of in de kop, bij de Aygo I, Yaris I en II, Corolla E12, Avensis II, RAV4 II en III en Prius II."),
            ("2010 – 2019", "Vaste sleutel of klapsleutel met knopjes, en een smartkey bij de hybrides, zoals de Yaris III, Auris, Avensis III, Verso, Prius III, C-HR I en RAV4 IV."),
            ("2019 en nieuwer", "Smartkey met keyless start, bij de Yaris IV, Yaris Cross, Corolla E210, C-HR II, RAV4 V, Aygo X en bZ4X.")],
     extra=[("Hybride", "De smartkey van een Toyota-hybride wordt op dezelfde manier aangemeld als bij een benzineauto. Het bouwjaar bepaalt vooral de prijs.")],
     modellen=["Aygo en Aygo X", "Yaris", "Yaris Cross", "Corolla en Corolla Cross", "C-HR", "RAV4", "Auris", "Avensis", "Verso", "Prius en Prius+", "Camry", "Highlander", "Land Cruiser", "Hilux", "Proace en Proace City", "bZ4X", "GT86 en GR86", "Supra"],
     faq=[("Wat kost een Toyota Yaris-sleutel?", "Een transpondersleutel vanaf € 60, een klapsleutel vanaf € 130 en een smartkey vanaf € 150, inclusief programmeren."),
          ("Mijn Aygo heeft een sleutel zonder knopjes.", "Dan is het een transpondersleutel: een kopie kost vanaf € 60."),
          ("Kan het zonder werkende Toyota-sleutel?", "Bij de meeste bouwjaren wel; de auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="Volkswagen", slug="volkswagen", prijsregel="vag", foto=("volkswagen-passat-smartkey-hengelo.jpg", "Twee Volkswagen-smartkeys in de hand, met de donkerblauwe Passat op de achtergrond", "Volkswagen Passat: twee smartkeys bijgemaakt"),
     intro="Polo, Golf, Passat, Tiguan, Caddy en Transporter: bij Volkswagen is de klapsleutel met drie knopjes al generaties de standaard. De nieuwere T-Roc, Tiguan en ID-modellen hebben vaak een smartkey. Omdat de systemen van de Volkswagen-groep per generatie verschillen, kan de prijs per model afwijken van de vanaf-prijs; de exacte prijs noemen wij op uw kenteken. Een sleutel voor de Up kost vanaf € 129.",
     typen=[("Tot ongeveer 2009", "Klapsleutel met chip en afstandsbediening, bij de Polo 9N, Golf IV en V, Passat B5 en B6, Touran I, Caddy III en Transporter T5."),
            ("2009 – 2017", "Klapsleutel van de nieuwere generatie, bij de Polo 6R, Golf VI en VII, Passat B7 en B8, Up, Tiguan I en Sharan II. Zonder werkende sleutel soms meer werk."),
            ("2017 en nieuwer", "Klapsleutel of smartkey met keyless, bij de Polo AW, Golf VIII, T-Roc, T-Cross, Tiguan II en III, Taigo en ID.3, ID.4 en ID. Buzz.")],
     extra=[("Volkswagen Up", "De Up is technisch gelijk aan de Škoda Citigo en Seat Mii. Een sleutel kost vanaf € 129, inclusief programmeren."),
            ("Caddy, Transporter en Crafter", "Bedrijfswagens van Volkswagen gebruiken dezelfde systemen als de personenauto's. Laat u twee sleutels tegelijk maken, dan krijgt u korting op de tweede, in overleg.")],
     modellen=["Up", "Polo", "Golf", "T-Cross", "Taigo", "T-Roc", "Tiguan", "Touran", "Passat", "Arteon", "Touareg", "Sharan", "ID.3", "ID.4", "ID.5", "ID.7", "ID. Buzz", "Caddy", "Transporter en Multivan", "Crafter", "Amarok", "Beetle", "Scirocco", "Fox", "Lupo"],
     faq=[("Wat kost een sleutel voor een Polo of Golf?", "Een klapsleutel vanaf € 130. Bij Volkswagen kan een model afwijken, dus uw kenteken bepaalt de precieze prijs."),
          ("Wat kost een Up-sleutel?", "Vanaf € 129, inclusief programmeren."),
          ("Kan het zonder werkende Volkswagen-sleutel?", "Bij de meeste bouwjaren wel. Sommige modellen vragen dan meer programmeerwerk; dat hoort u vooraf. Een enkel zeer recent model kan alleen via de dealer.")]),

dict(naam="Volvo", slug="volvo", prijsregel="staffel", foto=("volvo-v60-autosleutel-hengelo.jpg", "Volvo-sleutel met oranje hoes in de hand, met de grijze Volvo V60 op de achtergrond", "Volvo V60: sleutel bijgemaakt en ingeleerd"),
     intro="Volvo gebruikte rond 2000 een vaste sleutel met chip en afstandsbediening, daarna een klapsleutel of sleutel met knopjes, en sinds de XC90 van 2015 een smartkey met keyless start. Van V40 en V60 tot XC40 en XC60 maken wij Volvo-sleutels bij. Voor een enkele recente Volvo moet de sleutel via de dealer; dat checken wij vooraf op uw kenteken.",
     typen=[("Tot ongeveer 2004", "Vaste sleutel met chip en afstandsbediening, bij de S40 I, V40 I, S60 I, V70 II en S80 I."),
            ("2004 – 2015", "Klapsleutel of vaste sleutel met knopjes, soms keyless, bij de C30, S40 II, V50, V60 I, XC60 I, XC70 II en XC90 I."),
            ("2015 en nieuwer", "Smartkey met keyless start, bij de XC90 II, XC60 II, XC40, V60 II, V90, S90, C40 en EX30. Voor de allerjongste modellen is soms de dealer nodig.")],
     extra=[("Versleten rubbers", "De knopjes van een Volvo-sleutel slijten. Een nieuwe behuizing met uw eigen elektronica lost dat op zonder programmeren, vanaf € 35 voor een vaste sleutel.")],
     modellen=["XC40", "XC60", "XC70", "XC90", "V40", "V50", "V60", "V70", "V90", "S40", "S60", "S80", "S90", "C30", "C40", "C70", "EX30", "EX90", "850 en 940"],
     faq=[("Wat kost een sleutel voor een V60 of XC60?", "Een klapsleutel vanaf € 130, een smartkey vanaf € 150, inclusief programmeren."),
          ("Mijn Volvo-sleutel is versleten.", "Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 35 voor een vaste sleutel en vanaf € 49,95 voor een klapsleutel.")]),
]
