# Merken A t/m K. Feitenbron sleuteltypen/modellen: autosleutel-enschede data_merken.py; teksten eigen voor Hengelo.
# Velden: naam, slug, prijsregel ("staffel" | "vag" | "bmw" | "mercedes" | "psa" | "aanvraag"), foto (bestand, alt, onderschrift) of None,
#         intro, typen [(periode, tekst)], extra [(kop, alinea)], modellen [..], faq [(v, a)]

MERKEN_1 = [
dict(naam="Alfa Romeo", slug="alfa-romeo", prijsregel="staffel", foto=None,
     intro="Een Alfa Romeo kan drie soorten sleutels hebben, afhankelijk van het bouwjaar: een vaste sleutel met chip, een klapsleutel met knopjes of een smart key met startknop. De MiTo en Giulietta rijden meestal met een klapsleutel, de Giulia, Stelvio en Tonale met keyless. Alfa Romeo gebruikt al jaren de systemen van de Fiat-groep; die kennen wij goed. Welke sleutel uw Alfa heeft, zien wij aan uw kenteken.",
     typen=[("Tot ongeveer 2000", "Vaste sleutel met transponderchip, soms met een losse afstandsbediening. Wij maken een kopie van uw werkende sleutel."),
            ("2000 – 2015", "Klapsleutel met afstandsbediening in de behuizing, bijvoorbeeld bij de 147, 156, 159, GT, MiTo en Giulietta."),
            ("2016 en nieuwer", "Smart key met startknop bij de Giulia, Stelvio en Tonale. Het aanmelden gaat via de diagnoseaansluiting.")],
     extra=[("Oudere Alfa zonder werkende sleutel", "Bij sommige modellen uit de jaren 2000 is een kopie eenvoudig zolang er nog een werkende sleutel is. Bent u ze allemaal kwijt, dan kijken wij op uw kenteken wat bij uw bouwjaar mogelijk is en wat het kost.")],
     modellen=["145", "146", "147", "155", "156", "159", "166", "Brera en Spider", "GT", "GTV en Spider", "Giulia", "Giulietta", "MiTo", "Stelvio", "Tonale", "Junior"],
     faq=[("De klapsleutel van mijn MiTo klapt niet meer uit. Moet er een nieuwe komen?", "Meestal niet. Uw chip en zender gaan over in een nieuwe behuizing, vanaf € 49,95, zonder programmeren."),
          ("Maken jullie ook een smart key voor een Giulia of Stelvio?", "Voor de meeste bouwjaren wel. Stuur uw kenteken, dan hoort u vooraf of het bij uw uitvoering kan en wat het kost.")]),

dict(naam="Audi", slug="audi", prijsregel="vag", foto=None,
     intro="Audi deelt zijn sleuteltechniek met Volkswagen, Seat en Škoda. Een oudere A3 of A4 heeft vaak een klapsleutel, een jongere Q5, Q7 of e-tron een smart key met keyless start, en daartussen zitten generaties met een zwaardere beveiliging. Omdat die generaties flink verschillen, werken wij bij Audi met vanaf-prijzen. Met uw kenteken maken wij er vooraf één prijs van.",
     typen=[("Tot ongeveer 2008", "Klapsleutel met chip en afstandsbediening, zoals bij de A3 8L en 8P, de A4 B5 tot B7, de A6 C5 en de TT."),
            ("2008 – 2017", "Klapsleutel of smart key met de nieuwere startonderbreker. Zonder werkende sleutel is het bij een deel van deze modellen meer werk; dat hoort u vooraf."),
            ("2017 en nieuwer", "Smart key met keyless start, bijvoorbeeld bij de A4 B9, A5, Q5, Q7, Q8 en e-tron. De allernieuwste generatie gaat soms alleen via de dealer.")],
     extra=[("Behuizing versleten", "Bij Audi slijten de klapveer en de knopjes vaak eerder dan de elektronica. Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95 en hoeft niet opnieuw geprogrammeerd te worden.")],
     modellen=["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron en e-tron GT", "TT", "R8", "80 en 100"],
     faq=[("Waarom geven jullie bij Audi alleen vanaf-prijzen?", "Omdat de startonderbrekers van de Volkswagen-groep per generatie verschillen en sommige modellen meer werk vragen. Met uw kenteken wordt het één prijs vooraf."),
          ("Alle Audi-sleutels kwijt: kan er dan nog een smart key komen?", "Bij de meeste bouwjaren wel. De auto moet erbij zijn; de verloren sleutel wissen wij uit het geheugen."),
          ("Mijn Audi-klapsleutel is versleten. Werkt de chip nog?", "In de meeste gevallen wel. Dan is een nieuwe behuizing, vanaf € 49,95, voldoende.")]),

dict(naam="BMW", slug="bmw", prijsregel="bmw", foto=("bmw-x1-smartkey-bijmaken.jpg", "Twee bijgemaakte BMW-smartkeys in de hand, met de BMW X1 op de achtergrond", "BMW X1: twee smartkeys bijgemaakt in onze werkplaats"),
     intro="BMW beveiligt zijn sleutels zwaar, en elke generatie werkt anders: van de oudere sleutel met EWS-chip, via de smart keys voor de CAS- en FEM-systemen, tot de nieuwste smart keys van de G-serie. Wij maken BMW-sleutels bij, maar een vaste tabelprijs is er niet: u krijgt de prijs per model vooraf op uw kenteken. Een kopie van een originele BMW-sleutel van 2019 of nieuwer kost vanaf € 249.",
     typen=[("Tot ongeveer 2006", "Sleutel met EWS-chip en afstandsbediening, bijvoorbeeld bij de E36, E46, E39 en E53. Wij maken een kopie van uw werkende sleutel."),
            ("2006 – 2018", "Smart key voor de CAS- en FEM-systemen, zoals bij de E60, E90, F10, F30, X1, X3 en X5. Aanmelden gaat via de auto."),
            ("2019 en nieuwer", "Smart key van de nieuwste generatie, bijvoorbeeld bij de G-serie en de 1-serie F40. Een kopie van uw originele sleutel kost vanaf € 249.")],
     extra=[("Waarom prijs op aanvraag", "BMW-sleutels lopen per model en generatie te ver uiteen voor één prijs. Met uw kenteken weten wij welk systeem uw BMW heeft, of wij de sleutel kunnen maken en wat het kost. Bij een enkel model met de nieuwste beveiliging kan een bestelling via BMW nodig zijn; ook dat hoort u vooraf.")],
     modellen=["1-serie", "2-serie", "3-serie", "4-serie", "5-serie", "6-serie", "7-serie", "8-serie", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z3", "Z4", "i3", "i4", "iX"],
     faq=[("Waarom staat bij BMW geen prijs in de tabel?", "Omdat de sleutels per generatie en model te veel verschillen. Uw kenteken geeft vooraf de prijs."),
          ("Mijn BMW is van 2019 of later. Wat kost een kopie?", "Voor een originele sleutel van 2019 of nieuwer maken wij een kopie vanaf € 249."),
          ("Kunnen jullie een BMW-sleutel maken als alle sleutels kwijt zijn?", "Bij veel modellen wel, afhankelijk van de generatie. Stuur uw kenteken, dan hoort u het meteen.")]),

dict(naam="Citroën", slug="citroen", prijsregel="psa", foto=("citroen-c4-picasso-smartkey-bijmaken.jpg", "Twee bijgemaakte Citroën-sleutels in de hand, met de zwarte Citroën C4 Picasso op de achtergrond", "Citroën C4 Picasso: twee sleutels bijgemaakt"),
     intro="Citroën gebruikt de techniek van de PSA-groep, tegenwoordig Stellantis. Een Saxo of Xsara heeft een vaste sleutel of klapsleutel met chip, een C3, C4 of Berlingo uit de jaren daarna meestal een klapsleutel met twee of drie knopjes, en de jongste C3, C4 en C5 Aircross vaak een smart key. Is uw Citroën van ongeveer 2005 of ouder, dan hebben wij de pincode uit de autopapieren nodig.",
     typen=[("Tot ongeveer 2005", "Vaste sleutel of klapsleutel met chip, bijvoorbeeld bij de Saxo, Xsara, Xsara Picasso, Berlingo en de eerste C5. Voor het inleren is de pincode uit de autopapieren nodig."),
            ("2005 – 2016", "Klapsleutel met twee of drie knopjes, zoals bij de C1, C2, C3, C4, C4 Picasso en Berlingo II."),
            ("2016 en nieuwer", "Klapsleutel nieuwe stijl of smart key met startknop, bijvoorbeeld bij de C3 III, C4 III, C5 Aircross en Berlingo III.")],
     extra=[("Pincode kwijt", "Tot ongeveer 2005 vraagt een Citroën bij het inleren om een code die bij de autopapieren hoort. Heeft u die niet meer, dan vragen wij hem voor u op, vanaf € 35.")],
     modellen=["C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Cactus", "C4 Picasso en Grand C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C5 X", "C6", "C8", "Berlingo", "Jumpy", "Jumper", "Nemo", "Saxo", "Xsara en Xsara Picasso", "ë-C4", "Ami"],
     faq=[("Moet ik bij mijn Citroën de pincode bij de hand hebben?", "Alleen bij modellen tot ongeveer 2005. Zonder code vragen wij hem op, vanaf € 35."),
          ("Wat kost een Citroën-klapsleutel bijmaken?", "Vanaf € 130, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("De knopjes van mijn Citroën-sleutel reageren niet meer.", "Vaak is de behuizing versleten. Een nieuwe behuizing met uw eigen elektronica kost vanaf € 49,95.")]),

dict(naam="Dacia", slug="dacia", prijsregel="staffel", foto=None,
     intro="Onder een Dacia zit Renault-techniek. Een Logan, Sandero of Duster van de eerste generaties heeft een vaste sleutel met chip, met of zonder knopjes. De generatie daarna kreeg een vaste sleutel met drie knopjes, en de nieuwste Sandero, Duster en Jogger hebben vaak een sleutelkaart of smart key. Welke uw Dacia heeft, lezen wij uit het kenteken.",
     typen=[("2005 – 2012", "Vaste sleutel met chip, met of zonder afstandsbediening, bij de Logan I, Sandero I en Duster I."),
            ("2013 – 2020", "Vaste sleutel met drie knopjes, bij de Sandero II, Logan II, Duster II, Dokker en Lodgy."),
            ("2021 en nieuwer", "Sleutelkaart of smart key met startknop, bij de Sandero III, Duster III, Jogger en Spring.")],
     extra=[("Dacia-sleutelkaart", "De kaart van een nieuwe Dacia werkt zoals die van Renault: chip en zender zitten in de kaart zelf. Een nieuwe kaart melden wij aan op de auto; zijn alleen de knopjes kapot, dan repareren wij de kaart vaak.")],
     modellen=["Sandero en Sandero Stepway", "Logan en Logan MCV", "Duster", "Jogger", "Spring", "Dokker", "Lodgy", "Bigster"],
     faq=[("Wat betaal ik voor een extra Dacia-sleutel?", "Een transpondersleutel vanaf € 60, een sleutelkaart vanaf € 130 en een smart key vanaf € 150, inclusief programmeren."),
          ("Mijn Dacia-kaart werkt niet meer.", "Stuur een foto via WhatsApp of kom langs. Vaak zijn de knopjes te repareren; anders maken wij een nieuwe kaart."),
          ("Kan het zonder werkende sleutel?", "Bij vrijwel alle Dacia's wel. De auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="DS", slug="ds", prijsregel="staffel", foto=None,
     intro="DS begon als lijn binnen Citroën en is sinds 2015 een eigen merk, maar de sleuteltechniek komt nog steeds uit dezelfde groep. De DS 3, DS 4 en DS 5 uit de Citroën-periode hebben meestal een klapsleutel met drie knopjes. De DS 3 Crossback, de nieuwe DS 4 en de DS 7 werken met een smart key en startknop. Wij maken beide soorten bij.",
     typen=[("2010 – 2016", "Klapsleutel met drie knopjes, hetzelfde systeem als de Citroën C3, C4 en C5 van die jaren."),
            ("2016 en nieuwer", "Smart key met keyless start, bij de DS 3 Crossback, DS 4 II, DS 7 en DS 9. Voor de allerjongste uitvoeringen is soms de dealer nodig.")],
     extra=[("Twee sleutels tegelijk", "Heeft uw DS maar één sleutel, laat er dan meteen twee maken. Op de tweede krijgt u korting, in overleg.")],
     modellen=["DS 3", "DS 3 Cabrio", "DS 3 Crossback", "DS 4 en DS 4 Crossback", "DS 5", "DS 7 Crossback", "DS 9"],
     faq=[("Mijn DS 3 heeft een klapsleutel. Wat kost een tweede?", "Vanaf € 130, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("Maken jullie de smart key van een DS 7?", "Voor de meeste bouwjaren wel, vanaf € 150. Of het bij uw uitvoering lukt, weet u van tevoren.")]),

dict(naam="Fiat", slug="fiat", prijsregel="staffel", foto=("fiat-500-klapsleutel-bijmaken.jpg", "Twee Fiat-klapsleutels in de hand, met de witte Fiat 500 op de achtergrond", "Fiat 500: klapsleutel bijgemaakt"),
     intro="De klapsleutel met het ronde Fiat-logo hoort bij de 500, Panda, Punto en Tipo, en ook bij de Ducato. Oudere Fiats hebben een vaste sleutel met chip, de nieuwste 500e en 600 een smart key. Bij Fiat geven vooral de behuizing en de knopjes het op, terwijl de elektronica het nog doet. Repareren is dan vaak goedkoper dan een nieuwe sleutel.",
     typen=[("Tot ongeveer 2007", "Vaste sleutel met chip, vaak met losse of ingebouwde afstandsbediening, bij de Punto I en II, Seicento, Stilo en Doblò I."),
            ("2007 – 2020", "Klapsleutel met twee of drie knopjes, bij de 500, Panda, Grande Punto, Punto Evo, Tipo, Doblò II en Ducato."),
            ("2020 en nieuwer", "Smart key met startknop bij de 500e, 600 en uitvoeringen van de Tipo met keyless.")],
     extra=[("Fiat-klapsleutel kapot", "Versleten knopjes of een gebroken veer zien wij bij Fiat vaak. Nieuwe behuizing, uw eigen chip en zender erin, baard op code gefreesd: vanaf € 49,95, zonder programmeren.")],
     modellen=["500 en 500C", "500e", "500L", "500X", "600", "Panda", "Punto, Grande Punto en Punto Evo", "Tipo", "Bravo", "Stilo", "Idea", "Multipla", "Qubo", "Doblò", "Fiorino", "Scudo", "Talento", "Ducato", "Seicento", "Barchetta"],
     faq=[("Wat betaal ik voor een tweede klapsleutel van mijn 500?", "Vanaf € 130, inclusief programmeren. Alleen een nieuwe behuizing kost vanaf € 49,95."),
          ("Doen jullie ook een Ducato?", "Ja. Van Fiorino tot Ducato maken wij sleutels voor bedrijfswagens."),
          ("Alle sleutels van mijn Panda zijn weg.", "Bij de meeste bouwjaren maken wij een nieuwe sleutel en melden die aan op de auto. Uw kenteken geeft vooraf de prijs.")]),

dict(naam="Ford", slug="ford", prijsregel="staffel", foto=("ford-mustang-autosleutel-bijmaken.jpg", "Twee Ford-sleutels in de hand, met de blauwe Ford Mustang op de achtergrond", "Ford Mustang: twee sleutels bijgemaakt"),
     intro="Van de Fiesta en Focus tot de Kuga, Transit en Mustang: Ford-sleutels maken wij veel. Oudere Fords hebben een vaste sleutel met chip, de generatie daarna de bekende klapsleutel met drie knopjes, en de jongste Fiesta, Focus, Puma en Kuga een smart key. Ook bedrijfswagens als de Transit Custom en Transit Connect horen erbij.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip en meestal afstandsbediening, bij de Fiesta V, Focus I en II, Mondeo III, Ka I en Transit."),
            ("2008 – 2017", "Klapsleutel met drie knopjes, bij de Fiesta VI, Focus III, C-Max, Kuga I en II, B-Max en Transit Custom."),
            ("2017 en nieuwer", "Smart key met keyless start, bij de Fiesta VII, Focus IV, Puma, Kuga III, Mustang en Explorer.")],
     extra=[("Transit en andere bedrijfswagens", "Transit, Transit Custom, Transit Connect en Courier gebruiken dezelfde systemen als de personenauto's. Een tweede sleutel voorkomt dat de bus stilstaat als de enige sleutel zoekraakt.")],
     modellen=["Ka en Ka+", "Fiesta", "Focus", "Puma", "EcoSport", "Kuga", "Mondeo", "S-Max", "Galaxy", "C-Max en Grand C-Max", "B-Max", "Fusion", "Mustang en Mustang Mach-E", "Edge", "Explorer", "Ranger", "Transit Courier", "Transit Connect", "Transit Custom", "Transit", "Tourneo"],
     faq=[("Wat kost een Fiesta- of Focus-sleutel?", "Een klapsleutel vanaf € 130, een smart key vanaf € 150, inclusief programmeren. Het bouwjaar bepaalt de exacte prijs."),
          ("Mijn Ford-klapsleutel is gebroken.", "Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95."),
          ("Kunnen jullie aan huis een Transit-sleutel inleren?", "In veel gevallen wel. In Hengelo kost aan huis vanaf € 45 bovenop de sleutelprijs.")]),

dict(naam="Honda", slug="honda", prijsregel="staffel", foto=None,
     intro="Honda heeft per generatie een ander sleuteltype. Een Civic of Jazz van rond 2005 rijdt met een vaste sleutel met chip, een CR-V of Civic van na 2012 met een klapsleutel of smart key, en de nieuwste Jazz, HR-V en CR-V met keyless start. Wij maken Honda-sleutels bij en melden ze aan via de diagnoseaansluiting.",
     typen=[("Tot ongeveer 2006", "Vaste sleutel met chip, afstandsbediening los of in de kop, bij de Civic VII, Jazz I, CR-V II, HR-V I en Accord."),
            ("2006 – 2016", "Vaste sleutel of klapsleutel met knopjes, bij de Civic VIII en IX, Jazz II en III, CR-V III en IV en Insight. Sommige uitvoeringen hebben al een smart key."),
            ("2016 en nieuwer", "Smart key met keyless start, bij de Civic X en XI, Jazz IV, HR-V II en III, CR-V V en VI en e:Ny1.")],
     extra=[("Hybrides", "De Jazz e:HEV, CR-V Hybrid en Civic e:HEV hebben dezelfde smart key als de benzineversies. Het aanmelden gaat op dezelfde manier.")],
     modellen=["Jazz", "Civic", "Civic Type R", "HR-V", "CR-V", "ZR-V", "e:Ny1", "Honda e", "Accord", "Insight", "Legend", "FR-V", "Stream", "S2000", "CR-Z", "Prelude", "Logo"],
     faq=[("Wat betaal ik voor een tweede sleutel van mijn Jazz?", "Een transpondersleutel vanaf € 60, een sleutel met klapmechaniek vanaf € 130 en een smart key vanaf € 150, inclusief programmeren."),
          ("De afstandsbediening doet niets meer, maar de auto start wel.", "Dan is de chip in orde en zit het probleem in de zender of een knopje. Vaak te repareren, vanaf € 30.")]),

dict(naam="Hyundai", slug="hyundai", prijsregel="staffel", foto=("autosleutel-programmeren-hyundai.jpg", "Hyundai-sleutels worden ingeleerd met een programmeertablet via de diagnoseaansluiting", "Hyundai: sleutels inleren via de diagnoseaansluiting"),
     intro="Hyundai en Kia delen hun sleuteltechniek. Een Getz of Atos heeft een vaste sleutel met chip, een i10, i20 of i30 uit de jaren daarna meestal een klapsleutel met drie knopjes, en de Kona, Tucson en Ioniq van de laatste jaren een smart key. Wij melden Hyundai-sleutels aan via de diagnoseaansluiting, in de werkplaats of bij u voor de deur.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip, soms zonder afstandsbediening, bij de Atos, Getz, Accent, Santa Fe I en Tucson I."),
            ("2008 – 2017", "Klapsleutel met drie knopjes, bij de i10, i20, i30, ix20, ix35 en i40."),
            ("2017 en nieuwer", "Smart key met keyless start, bij de Kona, Tucson, Santa Fe, Ioniq, Ioniq 5 en 6 en Bayon.")],
     extra=[("Elektrische Hyundai", "De Kona Electric, Ioniq 5 en Ioniq 6 hebben een smart key die op dezelfde manier wordt aangemeld als bij de brandstofmodellen.")],
     modellen=["i10", "i20", "i30", "i40", "ix20", "ix35", "Kona en Kona Electric", "Bayon", "Tucson", "Santa Fe", "Ioniq", "Ioniq 5", "Ioniq 6", "Getz", "Atos", "Accent", "Matrix", "Coupé", "H-1 en H350"],
     faq=[("Wat kost een sleutel voor een i10 of i20?", "Een klapsleutel vanaf € 130, inclusief programmeren. Het bouwjaar bepaalt de exacte prijs."),
          ("Maken jullie een smart key voor een Kona?", "Ja, vanaf € 150. Uw kenteken geeft de exacte prijs."),
          ("De baard van mijn Hyundai-sleutel blijft binnen.", "Een nieuwe behuizing met uw eigen elektronica, vanaf € 49,95, zonder programmeren.")]),

dict(naam="Jaguar", slug="jaguar", prijsregel="staffel", foto=("jaguar-xf-smartkey-bijmaken.jpg", "Twee Jaguar-smartkeys in de hand, met de donkerblauwe Jaguar XF op de achtergrond", "Jaguar XF: smartkey bijgemaakt"),
     intro="Een oudere Jaguar zoals de X-Type of S-Type heeft een vaste sleutel met chip en afstandsbediening. Vanaf de XF en XJ van rond 2008 werkt Jaguar met een smart key en startknop, en de XE, F-Pace, E-Pace en I-Pace hebben een nieuwere keyless generatie. Jaguar en Land Rover delen hun sleutelsystemen; wat bij de een kan, geldt meestal ook bij de ander.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip en afstandsbediening, bij de X-Type, S-Type, XJ X350 en XK. Wij maken een kopie van uw werkende sleutel."),
            ("2008 – 2016", "Smart key met startknop, bij de XF I, XJ X351 en XK II."),
            ("2016 en nieuwer", "Smart key met keyless, bij de XE, XF II, F-Pace, E-Pace en I-Pace. Voor de allerjongste modellen is soms de dealer nodig.")],
     extra=[("Versleten knopjes", "De knopjes van een Jaguar-smart key slijten na jaren gebruik. Vaak is repareren of een nieuwe behuizing met uw eigen elektronica mogelijk. App ons een foto.")],
     modellen=["XE", "XF en XF Sportbrake", "XJ", "XK", "F-Type", "F-Pace", "E-Pace", "I-Pace", "X-Type", "S-Type"],
     faq=[("Wat kost een smart key voor een Jaguar XF?", "Vanaf € 150, inclusief programmeren. Uw kenteken geeft de exacte prijs."),
          ("Kan het zonder werkende Jaguar-sleutel?", "Bij de meeste bouwjaren wel. De auto moet erbij zijn, of wij komen aan huis.")]),

dict(naam="Jeep", slug="jeep", prijsregel="staffel", foto=("jeep-compass-smartkey-bijmaken.jpg", "Twee nieuwe smartkeys in een gehandschoende hand, met de witte Jeep Compass op de achtergrond", "Jeep Compass: twee smartkeys ingeleerd"),
     intro="Bij Jeep hangt het sleuteltype sterk af van het model. De Renegade en Compass van na 2014 delen hun techniek met Fiat en hebben een smart key met startknop. Een oudere Cherokee, Grand Cherokee of Wrangler gebruikt Chrysler-systemen met een vaste sleutel of klapsleutel. Wij maken beide soorten bij.",
     typen=[("Tot ongeveer 2014", "Vaste sleutel of klapsleutel met chip en afstandsbediening, bij de Cherokee, Grand Cherokee, Wrangler, Patriot en eerste Compass."),
            ("2014 en nieuwer", "Smart key met keyless start, bij de Renegade, Compass II, Grand Cherokee WL, Wrangler JL en Avenger.")],
     extra=[("Direct twee sleutels", "Bij een Jeep zonder reserve adviseren wij om meteen twee sleutels te laten maken. Op de tweede krijgt u korting, in overleg.")],
     modellen=["Avenger", "Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Patriot", "Commander"],
     faq=[("Wat kost een sleutel voor een Renegade of Compass?", "Een smart key vanaf € 150, inclusief programmeren. Het bouwjaar bepaalt de exacte prijs."),
          ("Alle sleutels van mijn Jeep zijn kwijt.", "Bij de meeste modellen maken wij een nieuwe sleutel en wissen wij de oude. Uw kenteken geeft vooraf de prijs."),
          ("Kan een oude Wrangler-sleutel ook?", "Ja. Dat is meestal een vaste sleutel met chip, vanaf € 60 als kopie van uw werkende sleutel.")]),

dict(naam="Kia", slug="kia", prijsregel="staffel", foto=None,
     intro="Kia gebruikt dezelfde sleuteltechniek als Hyundai. Een oudere Picanto of Rio rijdt met een vaste sleutel met chip, de Picanto, Rio en Ceed van de volgende generatie met een klapsleutel, en de Niro, Sportage, Soul en EV-modellen met een smart key. Uw kenteken vertelt ons welke generatie uw Kia heeft.",
     typen=[("Tot ongeveer 2008", "Vaste sleutel met chip, met of zonder afstandsbediening, bij de Picanto I, Rio II, Carens en Sorento I."),
            ("2008 – 2017", "Klapsleutel met drie knopjes, bij de Picanto II, Rio III, Ceed I en II, Venga en Sportage III."),
            ("2017 en nieuwer", "Smart key met keyless start, bij de Ceed III, Stonic, Niro, Sportage IV en V, Soul EV, EV6 en EV9.")],
     extra=[("Elektrische Kia", "De Soul EV, Niro EV, EV6 en EV9 hebben een smart key die wij op dezelfde manier aanmelden als bij de brandstofmodellen.")],
     modellen=["Picanto", "Rio", "Stonic", "Ceed, Pro_Cee'd en XCeed", "Niro", "Soul en Soul EV", "Sportage", "Sorento", "EV6", "EV9", "Carens", "Venga", "Optima", "Stinger", "Cerato", "Carnival"],
     faq=[("Wat betaal ik voor een extra sleutel van een Picanto?", "Een transpondersleutel vanaf € 60, een klapsleutel vanaf € 130, inclusief programmeren."),
          ("Maken jullie een smart key voor een Niro of Sportage?", "Voor de meeste bouwjaren wel, vanaf € 150."),
          ("Mijn Kia-klapsleutel is gebroken.", "Een nieuwe behuizing met uw eigen chip en zender kost vanaf € 49,95.")]),
]
